### ISSUE TITLE
Автокомплит

### ISSUE THREAD

**Issue by HawkeyePierce89** [knigopis/repo.knigopis.com#1]
Было бы неплохо добавить автокомплит по AJAX, когда пишешь название книги в форме добавления записи о прочитанной книге

**Comment by knigopis** [comment]
Для этого потребуется либо держать свою базу книг, либо использовать сторонние сервисы. Оба варианта противоречат идеологии проекта, а именно - `Долговечности`, так как в первом случае базу нужно поддерживать и обновлять, а во втором добавляет лишнюю зависимость. Можно было бы использовать Google APIS: `https://www.googleapis.com/books/v1/volumes?q=title:%D0%BA%D0%BE%D1%82%D1%8B`, но я не вижу существенных преимуществ, когда у нас `Свобода ввода`.

**Comment by HawkeyePierce89** [comment]
«в первом случае базу нужно поддерживать и обновлять»
Простите, а у вас сайт о чём? Зачем ещё отдельная база, если на основе уже существующих данных можно составить достаточную для автокомплита подборку книг+автор и ещё и иметь статистику наиболее популярных книг, чтобы выдавать не по алфавиту, а по частоте предыдущих добавлений.

«я не вижу существенных преимуществ»
У — удобство, когда тебе лень заполнять название книги из 5-7 слов, а потом ещё вспоминать как правильно пишется имя и фамилия автора.
